[[collects]]
  repository = "https://github.com/google/fonts"
  requests = [
    "ufl/ubuntu/Ubuntu-Medium.ttf",
    "ufl/ubuntu/Ubuntu-MediumItalic.ttf",
  ]
  version = "master"
  dir = "fonts"

[[collects]]
  repository = "https://github.com/Microsoft/fonts"
  requests = [
    "Symbols/winjs-symbols.ttf",
  ]
  version = "master"
  dir = "fonts"